version: '3'

networks:
  sh:

services:
  mongodb:
    image: mongo:latest
    volumes:
    - ./data:/data/db
    expose: 
      - 27017
    networks:
      - sh

  redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      - sh

  secret-hitler:
    build: .
    depends_on:
      - mongodb
      - redis
    networks:
      - sh
    restart: always
    environment: 
      MONGODB_URI: mongodb://mongodb:27017
      REDIS_HOST: redis
      SECRETSESSIONKEY: hunter2
    ports:
      - 8080:8080
