apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-hitler
  name: secret-hitler
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: secret-hitler
  type: NodePort
