apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-hitler
  name: secret-hitler-load-balancer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: secret-hitler
  type: LoadBalancer
